### ISSUE TITLE
a way to remove your proposed move

### ISSUE THREAD

**Issue by karlorg** [karlorg/drunken-octo-avenger#34]
maybe clicking off the board could remove a new stone, if you've placed one?  Helpful, or surprising?  Maybe just add a new button, eg. at the bottom right, that clears the proposed stone.

**Comment by allanderek** [comment]
Refresh would also do it. I thought about adding a button to refresh for the chat, but I'm disinclined to add a button that most browsers already have a button for (plus I thought we would eventually make it so that the chat updated itself).

I'm not against this idea but I'm not desperate for it either.

**Comment by karlorg** [comment]
On 27/06/2015 21:17, allanderek wrote:
> Refresh would also do it. I thought about adding a button to refresh for
> the chat, but I'm disinclined to add a button that most browsers already
> have a button for (plus I thought we would eventually make it so that
> the chat updated itself).

Oh hey you get notified of these?  Feel free to add any features you 
think we should add in future.

Yeah I noticed that back button worked (maybe only when you've played a 
move already, so 'back' still goes to the game page), or refresh, but 
those might not occur to people.  I'd like to have some obvious way to 
do it, and it might be nice to cater to the expectation that clicking 
off the board should remove the stone, as long as that doesn't surprise 
people -- it'd have to not do that when clicking on chat, for instance :/

> I'm not against this idea but I'm not desperate for it either.

Yeah, I'm just shoving stuff in Issues as a reminder to get to them at 
some point.
