### ISSUE TITLE
view past moves on the game page

### ISSUE THREAD

**Issue by karlorg** [karlorg/drunken-octo-avenger#35]
eg. via forward/back controls or a DGS-style dropdown list of moves.

**Comment by allanderek** [comment]
Is this now completed? I think we have this? I would personally quite like back and forward by one move buttons, but it at least currently works the way I think this original issue suggested.

**Comment by karlorg** [comment]
That would be nice yeah.  Want to open a new issue and close this?

**Comment by allanderek** [comment]
Okay sure.
