### ISSUE TITLE
Color Enums

### ISSUE THREAD

**Issue by allanderek** [karlorg/drunken-octo-avenger#53]
There are Color enums defined in both 'go.py' and 'go_rules.py', this cannot be good? They are defined to be the same, but surely that is just asking for someone to change one and not the other.

**Comment by karlorg** [comment]
tbh I'm not even sure go_rules is used any more, that might be a vestige 
of the old architecture.

**Comment by allanderek** [comment]
You were correct it was legacy/dead code. I removed it in the p3-and-cleanup branch.
