### ISSUE TITLE
reports "All tests passed!" despite casper test failures

### ISSUE THREAD

**Issue by karlorg** [karlorg/drunken-octo-avenger#59]

**Comment by allanderek** [comment]
I believe I have fixed this in the p3-and-cleanup branch.

**Comment by karlorg** [comment]
oh right I see

**Comment by allanderek** [comment]
I know, that branch was probably larger than it should have been, containing more work than it should have.

**Comment by karlorg** [comment]
nah it's just that I didn't notice some of it was not on master at first, so I just checked out allan/master and tested that.  Testing the p3-... branch now.
