### ISSUE TITLE
Browser tests not under coverage

### ISSUE THREAD

**Issue by karlorg** [karlorg/drunken-octo-avenger#7]
Running just the browser tests under coverage shows that they're not being counted toward test coverage.  Not sure why; maybe the COVERAGE_PROCESS_START environment variable isn't being propagated to whatever subprocesses are running the test server?

**Comment by allanderek** [comment]
Good question, I'll look into it.

**Comment by karlorg** [comment]
Might also be worth thinking about whether `browser_tests/base.py` -> `create_app` needs anything added to facilitate this

**Comment by allanderek** [comment]
Hey, I am  not sure what you meant by "not being counted toward test coverage". How did you run "just the browser tests under coverage"?

Running:

    python manage.py coverage 

I get:

    OK
    Name                                 Stmts   Miss Branch BrMiss  Cover   Missing
    --------------------------------------------------------------------------------
    app/__init__                             0      0      0      0   100%   
    app/browser_tests/__init__               0      0      0      0   100%   
    app/browser_tests/base                 103     13     30      9    83%   38-52, 67, 103, 124, 142, 153
    app/browser_tests/fabfile               16     16      0      0     0%   1-38
    app/browser_tests/server_tools          27     13      4      4    45%   24-28, 31-42, 46, 52, 62-65
    app/browser_tests/test_frontpage        57      6      6      2    87%   23-25, 45, 92, 99
    app/browser_tests/test_game             92      9      6      3    88%   21, 26-27, 40, 45-46, 103-104, 107
    app/browser_tests/test_start_games      40      0      0      0   100%   
    app/browser_tests/test_status           28      0      0      0   100%   
    app/main                               174      1     42      1    99%   73
    app/tests/__init__                       0      0      0      0   100%   
    app/tests/test                         299      0      4      0   100%   
    --------------------------------------------------------------------------------
    TOTAL                                  836     58     92     19    92%   

Which to me looks like they are being counted towards coverage.
I think you ran a command something like:

    COVERAGE_PROCESS_START=.coveragerc coverage run --source app manage.py test_package app.browser_tests

I guess what I'm asking is, what did you run, what did you expect, and what did you get?

**Comment by karlorg** [comment]
I hacked `manage.py` to run `test_package app.browser_tests` instead of `test_all`, and the coverage of `app/main` dropped to 26% -- none of the view functions are touched at all.  Browser tests may not be as exhaustive as unit tests, but they should at least hit each view function, and there may be lines of code that are /only/ touched by browser tests.  (There's currently one such line, at the end of the `challenge` view function -- it seems to make more sense to test the form by visiting it in the browser and filling it in, rather than examining the returned HTML in a unit test.)

**Comment by allanderek** [comment]
So if I understand you correctly, you did, hacked `manage.py` to something like:

    @manager.command
    def coverage(quick=False):
        rcpath = os.path.abspath('.coveragerc')
        manage_command = (
                'test_package app.tests' if quick else 'test_package app.browser_tests' # 'test_all'
        )

If I do the same I still get:

    OK
    Name                                 Stmts   Miss Branch BrMiss  Cover   Missing
    --------------------------------------------------------------------------------
    app/__init__                             0      0      0      0   100%   
    app/browser_tests/__init__               0      0      0      0   100%   
    app/browser_tests/base                 103     12     30      8    85%   38-52, 67, 124, 142, 153
    app/browser_tests/fabfile               16     16      0      0     0%   1-38
    app/browser_tests/server_tools          27     13      4      4    45%   24-28, 31-42, 46, 52, 62-65
    app/browser_tests/test_frontpage        57      6      6      2    87%   23-25, 45, 92, 99
    app/browser_tests/test_game             92      9      6      3    88%   21, 26-27, 40, 45-46, 103-104, 107
    app/browser_tests/test_start_games      40      0      0      0   100%   
    app/browser_tests/test_status           28      0      0      0   100%   
    app/main                               174      1     42      1    99%   73
    app/tests/__init__                       0      0      0      0   100%   
    app/tests/test                         299      0      4      0   100%   
    --------------------------------------------------------------------------------
    TOTAL                                  836     57     92     18    92%   

So I'm struggling to reproduce this.

**Comment by karlorg** [comment]
oh, seems you have to `rm .coverage` first to clear out the results from earlier coverage runs

**Comment by allanderek** [comment]
Ah I see. I'll investigate this tomorrow. Also, I'll add something to
manage.py to automatically delete any existing `.coverage` file.

**Comment by karlorg** [comment]
OK cool.  I may get back to it myself, but for today I'm kinda burned out on investigating this one :(

**Comment by allanderek** [comment]
Some more investigation. It seems that coverage is known not to work with processes that are forked with `multiprocessing` rather than `subprocess`. There is an [experimental fix](https://bitbucket.org/ned/coveragepy/commits/f84263e515c2) for it in the development version of coverage.py. The [issue is explained here](https://bitbucket.org/ned/coveragepy/issue/117/enable-coverage-measurement-of-code-run-by).

The problem is that 'Flask.ext.testing' uses `multiprocessing` there are a couple of plausible fixes, one of which is to simply wait until the updated coverage.py is released. Another of which is to write our own version of LiveServerTest that uses `subprocess` rather than `multiprocessing`.

**Comment by allanderek** [comment]
A bit more investigation. I thought about simply using the workaround proposed in the multiprocessing issue linked to above. With the intention of leaving a comment saying to remove that workaround whenever the next version of coverage.py is released.

However, there is a significant issue with this. The subprocess, however we fork it, is terminated, which means coverage never gets the chance to write the coverage data.

**Comment by karlorg** [comment]
On 12.02.2015 15:24, allanderek wrote:

> However, there is a significant issue with this. The subprocess, however
> we fork it, is terminated, which means coverage never gets the chance to
> write the coverage data.

It is only one line so far that's not shown as hit and should be.  We 
could wait and see if the experimental coverage upgrade gets released? 
Or would that just have the same problem?

**Comment by allanderek** [comment]
Well, I think you're right that it would be nice to know how exhaustive the browser tests by themselves are. I think even with the update to coverage we suffer the same problem. I was going to suggest adding a manage.py command that runs just the browser tests.

However, I think it's probably worth mulling this over for a while.

**Comment by karlorg** [comment]
no longer an issue with our CasperJS test runner
